server:
  port: 6677
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://139.224.33.91:3306/web?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xiaowang.htmlstudy.model.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
